name: startup_database
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  rxdart: ^0.24.1
  flutter_bloc: ^6.0.6
  firebase_core : ^0.5.0
  firebase_auth: ^0.18.1+1
  cloud_firestore: ^0.14.1+2
  provider: ^4.3.2+2
  flutter_spinkit: "^4.1.2"
  eva_icons_flutter: ^2.0.1
  table_calendar: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/

